---
 - hosts: all
   become: true
   gather_facts: yes
   tasks: 
    - name: configure repo
      ansible.builtin.copy:
        src: /home/nmohan/RHEL7_MGMT.repo
        dest: /etc/yum.repos.d        
    - name: configure chrony
      ansible.builtin.yum: 
        name: chrony
        state: latest
        update_cache: yes        
    - name: update chrony    
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        insertbefore: 'server 0.rhel.pool.ntp.org iburst'
        line: 'server 172.17.8.0 iburst'
    - name: copy the rpm
      ansible.builtin.copy:
        src: /home/s-ansibleuser/
        dest: /tmp/
    - name: install the package
      ansible.builtin.yum:
        name: /tmp/package
        state: present
        test: nithin